# Generated by Django 3.2.7 on 2024-02-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_mod', '0003_advocate_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='about',
            field=models.CharField(max_length=800),
        ),
    ]
