# Generated by Django 3.2.7 on 2024-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=15)),
                ('uemail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
