# Generated by Django 3.2.7 on 2024-01-31 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate_mod', '0002_advocate_status'),
        ('user_mod', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advocate_mod.advocate'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_aname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
