# Generated by Django 3.2.7 on 2024-02-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mod', '0003_auto_20240131_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
