# Generated by Django 3.2.7 on 2024-02-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mod', '0005_alter_appointment_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='uid',
        ),
    ]
