# Generated by Django 3.2.7 on 2024-02-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mod', '0008_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment',
            field=models.CharField(default='waiting for approval', max_length=50),
        ),
    ]
